[package]
name = "dynamic_ocl"
version = "0.1.0-alpha"
authors = ["Dominic Marcuse <dominic@marcuse.us>"]
edition = "2018"

[dependencies]
libc = "0.2.66"
dlopen = "0.1.8"
thiserror = "1.0.9"
lazy_static = "1.4.0"
const-cstr = "0.3.0"
generic-array = "0.13.2"
log = "0.4.8"
